### ISSUE TITLE
fragment Tag FragmentContainerView Replace

### ISSUE THREAD

**Issue by yongrokkwon** [DDD-3/3-Android-Untitled#11]
린트로 변경하라고 나옴 이미지 참고
![image](https://user-images.githubusercontent.com/15951322/69974349-698f4300-1568-11ea-85b1-ce9c6183273a.png)

**Comment by ojh102** [comment]
https://issuetracker.google.com/issues/143752103
지금 변경하면 Fragment안의 바텀네비게이션에서 그래프가 제대로 동작하지 않는 이슈가 있습니다.
2.2.0-rc03에서는 해결된거 같으니 릴리즈 될떄까지 잠시 기다리는게 좋겠습니다.😂
